### ISSUE TITLE
Support for uploading Test run package

### ISSUE THREAD

**Issue by sanyam-coursera** [peartherapeutics/bitrise-aws-device-farm-runner#10]
Hi,

I was wondering if you tried adding the functionality for uploading a test package (along with the app upload), instead of using an existing test package? I read through the AWS CLI apis and the test package can be uploaded in a very similar way:

`aws devicefarm create-upload --project-arn <project arn> --name <test package file path> --type XCTEST_TEST_PACKAGE`

This will have a similar response to when you upload an app, containing the test package ARN.

**Comment by fadookie** [comment]
Yes, I have a separate step that can upload any file to device farm: https://github.com/peartherapeutics/bitrise-aws-device-farm-file-deploy

This step is designed to use the latest file with a given name. There is an open issue with the file deploy step to export the upload ARN... I'd be happy to take a PR with this functionality.

**Comment by sanyam-coursera** [comment]
Oh thats helpful, using the file deploy step was ideal. Thanks!
