### ISSUE TITLE
testing with unmetered device slot

### ISSUE THREAD

**Issue by andreschab90** [peartherapeutics/bitrise-aws-device-farm-runner#22]
Does the runner use the purchased device slot, when i started a test run?!
Is there a possibilty to use the unmetered billing with your runner?

best regards
André

**Comment by fadookie** [comment]
@andreschab90 I'm not sure. I have not used purchased device slots yet. I'd suggest you have a look at the [device farm docs](https://aws.amazon.com/documentation/devicefarm/) to see if you can find any info on that.

Maybe you could try kicking off a test run and then check your metering/billing information afterwards to see if it was billed correctly?

**Comment by andreschab90** [comment]
@fadookie i can confirm, that this device runner works only for the metered billing method. i have purchased a device slot, but the runner still uses the metered billing method. If i set up a test manually via the webUI, then i have to choose the billig method. The default billing method ist "metering"

**Comment by fadookie** [comment]
@andreschab90 Thanks. Looks like `ScheduleRun` endpoint takes an (optional) `billingMethod` property: https://docs.aws.amazon.com/devicefarm/latest/APIReference/API_ScheduleRunConfiguration.html#devicefarm-Type-ScheduleRunConfiguration-billingMethod

I don't have time to make this change myself but I'd be open to a PR that adds billing method as an optional input to this step. It should be passed to aws-cli via the `--configuration` flag: https://docs.aws.amazon.com/cli/latest/reference/devicefarm/schedule-run.html
Relevant step code is at https://github.com/peartherapeutics/bitrise-aws-device-farm-runner/blob/master/step.sh#L188

**Comment by andreschab90** [comment]
@fadookie PR is created

**Comment by fadookie** [comment]
closed by https://github.com/peartherapeutics/bitrise-aws-device-farm-runner/pull/26
