### ISSUE TITLE
Allow specifying the test-spec ARN

### ISSUE THREAD

**Issue by LukasKnuthImagineOn** [peartherapeutics/bitrise-aws-device-farm-runner#46]
When running the [`schedule-run`-command](https://docs.aws.amazon.com/cli/latest/reference/devicefarm/schedule-run.html) via the AWS CLI, one can specify the test-spec that should be used for the run via the `--test`-flags `testSpecArn` property.

This would allow the user to create a test-spec in the AWS UI or CLI and specify it for a run, giving more control over the actual environment and process on the AWS Device Farm.

**Comment by fadookie** [comment]
I don't have time to add this right now but I am open to a backwards-compatible PR.

**Comment by Donmclean** [comment]
Related Bitrise Issue: https://discuss.bitrise.io/t/aws-device-farm-runner-does-not-support-custom-tests/7957

**Comment by fadookie** [comment]
Thanks for the heads up. This is a more appropriate place for issues and feature requests related to this step. I am still the maintainer of this step, not bitrise (at least for now) although unfortunately I don't really have time to add features myself anymore. But like I said I am happy to review PRs to and will take them if the changes have been tested and are backwards-compatible.

**Comment by GuillaumeHemmen** [comment]
Why not merging https://github.com/ginmon/bitrise-aws-device-farm-runner? He implemented `test_spec` to do that.

**Comment by fadookie** [comment]
@GuillaumeHemmen Like I said, feel free to send a PR. I don't have time to work on this myself now but I will try to carve out some time to at least review PRs.

**Comment by elashpear** [comment]
Goodness, I only just noticed you were linking to a fork. Nobody sent me a PR so I never noticed.

I opened https://github.com/peartherapeutics/bitrise-aws-device-farm-runner/pull/51 to track these changes and will try to review them soon.
