### ISSUE TITLE
aws-device-farm-runner (exit code: 255) 

### ISSUE THREAD

**Issue by zebpaysagar** [peartherapeutics/bitrise-aws-device-farm-runner#49]
We are facing and issue while configuring the aws device farm with the trigger in the bitrise.
following is the log from the bitrise.

`
+------------------------------------------------------------------------------+

| (4) aws-device-farm-runner                                                   |
+------------------------------------------------------------------------------+
| id: aws-device-farm-runner                                                   |
| version: 0.0.7                                                               |
| collection: https://github.com/bitrise-io/bitrise-steplib.git                |
| toolkit: bash                                                                |
| time: 2019-02-04T14:22:37Z                                                   |
+------------------------------------------------------------------------------+
|                                                                              |
INFO[14:22:37]  * [OK] Step dependency (aws) installed, available. 
INFO[14:22:37] Start installing (jq) with apt-get           
sudo "apt-get" "update"
Get:1 http://security.ubuntu.com/ubuntu xenial-security InRelease [109 kB]
Get:2 https://packages.cloud.google.com/apt cloud-sdk-xenial InRelease [6,372 B]
Hit:3 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:4 https://deb.nodesource.com/node_8.x xenial InRelease [4,646 B]
Get:5 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [109 kB]
Get:6 https://download.docker.com/linux/ubuntu xenial InRelease [66.2 kB]
Hit:7 https://dl.yarnpkg.com/debian stable InRelease
Get:8 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [779 kB]
Get:9 http://security.ubuntu.com/ubuntu xenial-security/main i386 Packages [658 kB]
Get:10 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [535 kB]
Get:11 http://security.ubuntu.com/ubuntu xenial-security/universe i386 Packages [464 kB]
Get:12 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [107 kB]
Hit:13 https://packagecloud.io/github/git-lfs/ubuntu xenial InRelease
Get:14 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [1,175 kB]
Get:15 http://archive.ubuntu.com/ubuntu xenial-updates/main i386 Packages [1,032 kB]
Get:16 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [936 kB]
Get:17 http://archive.ubuntu.com/ubuntu xenial-updates/universe i386 Packages [856 kB]
Fetched 6,837 kB in 1s (3,730 kB/s)
Reading package lists...
(jq) isn't installed, installing...
 * [OK] jq installed
INFO[14:22:46]  * [OK] Step dependency (jq) installed, available. 
Configs:
  * access_key_id: ***
  * secret_access_key: ***
  * device_farm_project: [REDACTED]
  * test_package_name: [REDACTED]-development-debug-androidTest.apk
  * test_type: INSTRUMENTATION
  * filter: 
  * billing_method: METERED
  * locale: en_US
  * platform: android
  * ipa_path: 
  * ios_pool: 
  * apk_path: /bitrise/deploy/[REDACTED]-development-debug-androidTest.apk
    * run_name_prefix: 
  * build_version: 6128
  * aws_region: [REDACTED]
  * run_wait_for_results: true
  * run_fail_on_warning: false
  AWS region ([REDACTED]) specified!
Setting up device farm run for platform 'android'.
  * run_platform: android
    * app_package_path: /bitrise/deploy/[REDACTED]-development-debug-androidTest.apk
  * upload_type: ANDROID_APP
    Initialized upload of package '[REDACTED]-development-debug-androidTest.apk' for app ARN 'ARN'
  Beginning upload
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 2024k    0     0  100 2024k      0  2442k --:--:-- --:--:-- --:--:-- 2444k
  Upload finished. Polling for status.
  Upload status: SUCCEEDED
  Upload successful! Starting run...
An error occurred (NotFoundException) when calling the ScheduleRun operation: One or more of the resources for this request are not available.
|                                                                              |
+---+---------------------------------------------------------------+----------+
| x | aws-device-farm-runner (exit code: 255)                       | 14 sec   |
+---+---------------------------------------------------------------+----------+
| Issue tracker: ...com/peartherapeutics/bitrise-aws-device-farm-runner/issues |
| Source: https://github.com/peartherapeutics/bitrise-aws-device-farm-runner   |
+---+---------------------------------------------------------------+----------+
`

**Comment by fadookie** [comment]
`test_package_name` should be the name of the test uploaded by the file deploy step as explained in the docs. This should be different from the actual app bundle as specified in `apk_path`. Please read the wiki and inline step input documentation thoroughly. If you ar still having issues after that you can re-open.
